name: Platformer Generated platformer-workflow Build
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/sliit-foss/rsvp
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_634EBED6_CA09_4B11_80AC_2A421955481C }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_F8DCF125_5ECD_47D5_BCB2_6479B0A6FE5F}}
          project-id: ${{secrets.PROJECT_ID_F8DCF125_5ECD_47D5_BCB2_6479B0A6FE5F}}
          token: ${{secrets.AUTOGENERATED_CICD_F8DCF125_5ECD_47D5_BCB2_6479B0A6FE5F}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 1c2cf09f-e449-45e6-a7dc-7a62a4f6faf8
